### ISSUE TITLE
Criar um esboço para o design do website

### ISSUE THREAD

**Issue by marshfellow42** [marshfellow42/WikiForge#3]

**Comment by marshfellow42** [comment]
![1731507065027](https://github.com/user-attachments/assets/c9e34d07-39c9-4a67-9dd1-e42efb44f440)

**Comment by marshfellow42** [comment]
![1731507125703](https://github.com/user-attachments/assets/ea9f1862-528c-4159-982a-d14be3441fb6)

**Comment by marshfellow42** [comment]
@Elbston

**Comment by Elbston** [comment]
![CamScanner 26-11-2024 13.52.jpg](https://github.com/user-attachments/assets/ec408297-33e3-4322-ae3b-d9683a584a0e)
